services:
  # Include all services from docker-compose-gizilens.yml
  postgres:
    extends:
      file: docker-compose-gizilens.yml
      service: postgres

  redis:
    extends:
      file: docker-compose-gizilens.yml
      service: redis

  nginx:
    extends:
      file: docker-compose-gizilens.yml
      service: nginx

  # Include all services from docker-compose-server.yml
  backend:
    extends:
      file: docker-compose-server.yml
      service: backend
    depends_on:
      - postgres
      - redis

  frontend:
    extends:
      file: docker-compose-server.yml
      service: frontend
    depends_on:
      - backend

networks:
  gizilens_network:
    external: true
