services:
  backend:
    image: farismnrr/gizilens-backend:latest
    container_name: backend-prod
    restart: always
    ports:
      - "5500:5500"
    volumes:
      - ./backend/data:/app/data
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_PROD=postgres
      - REDIS_HOST_PROD=redis
    networks:
      - gizilens_network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  frontend:
    image: farismnrr/gizilens-frontend:latest
    container_name: frontend-prod
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/data:/app/data
    env_file:
      - .env
    environment:
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
    networks:
      - gizilens_network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  gizilens_network:
    external: true
